use customer_behaviour;
select * from customer_shopping_behavior;
--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as total_revenue from customer_shopping_behavior
group by gender ;
--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select * from customer_shopping_behavior 
where discount_applied  = 'yes' 
and purchase_amount >(select avg(purchase_amount) from customer_shopping_behavior);
-- Q3. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased , round(avg(review_rating),2) as Highest_average_review 
from customer_shopping_behavior 
group by item_purchased 
order by Highest_average_review desc;
--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type , round(avg(purchase_amount),2) as average_purchase
from customer_shopping_behavior
where shipping_type in ( 'express' , 'standard')
group by shipping_type ;
--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer_shopping_behavior
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;
--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT top 5 item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),1) AS discount_rate
FROM customer_shopping_behavior
GROUP BY item_purchased
ORDER BY discount_rate DESC
;

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer_shopping_behavior)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 

WITH ITEM_COUNT AS( SELECT CATEGORY, item_purchased,
COUNT(CUSTOMER_iD) AS TOTAL_ORDERS,
ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY COUNT(CUSTOMER_ID) DESC) AS ITEM_RANK 
FROM customer_shopping_behavior
GROUP BY CATEGORY, item_purchased 
) 
SELECT  ITEM_RANK ,  CATEGORY , item_purchased, 
TOTAL_ORDERS FROM ITEM_COUNT
where item_rank <=3;
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select  subscription_status,
count(customer_id) as repeted_buyer
from customer_shopping_behavior
where previous_purchases > 5 
group by  subscription_status
;
--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer_shopping_behavior
GROUP BY age_group
ORDER BY total_revenue desc;
 
